from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from standard_user.views import update_maintenance, cancel_maintenance, confirm_ticket_status, \
    user_ratings, training_rate, maintenance_rate, update_pending_laminator, cancel_pending_laminator, \
    update_pending_mrw, cancel_pending_mrw, update_pending_iss, cancel_pending_iss

urlpatterns = [
    path('', views.home, name="home"),
    path('account/login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('helpdesk', views.helpdesk_options, name='helpdesk'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.admin_activate, name='admin_activate'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.
         as_view(template_name='users/password_reset/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.
         as_view(template_name='users/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.
         as_view(template_name='users/password_reset/password_reset_complete.html'), name='password_reset_complete'),
    path('inactive_users', views.inactive_users, name="inactive_users"),
    path('activate_user/<str:pk>', views.activate_user, name="activate_user"),
    path('active_users', views.active_users, name="active_users"),
    path('deactivate_user/<str:pk>', views.deactivate_user, name='deactivate_user'),
    path('report/user', views.user_report, name="user_report"),
    path('details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.user_report_details,
         name='user_report_details'),
    path('parts_breakdown/<str:pk>/<str:name>/<str:period>/<str:date>/<str:date2>', views.user_part_report_details,
         name='user_part_report_details'),
    path('part_details/<str:name>', views.part_report_details, name='part_report_details'),
    path('users/management/options', views.user_management, name="user_management"),
    path('clients/management/options', views.client_options, name="client_options"),
    path('client/add', views.add_client, name="add_client"),
    path('update_client/<str:pk>', views.update_client, name='update_client'),
    path('report/clients', views.clients, name="clients"),
    path('report/client/printers', views.client_report, name="client_report"),
    path('client_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.client_report_details,
         name='client_report_details'),
    path('report/printers/pending', views.maintenance, name="maintenance"),
    path('report/delay/maintenance/pending', views.delay_maintenances, name="delay_maintenances"),
    path('reports/maintenance/printers/occurrence/detailed', views.maintenance_occurrence, name='maintenance_occurrence'),
    path('update_maintenance/<str:pk>', views.update_maintenance, name='update_maintenance'),
    path('cancel_maintenance/<str:pk>', views.cancel_maintenance, name='cancel_maintenance'),
    path('reports/clients/fixed/printers', views.fixed_printers, name="fixed_printers"),
    path('report/cancelled/schedules/printers', views.cancelled_schedules, name="cancelled_schedules"),
    path('reports/fixed/not_delivered/printers', views.fixed_undelivered_printers, name="fixed_undelivered_printers"),
    path('printer/rma/request', views.add_rma, name="add_rma"),
    path('report/printers/rma/requests', views.rma_requests, name="rma_requests"),
    path('update_rma/<str:pk>', views.update_rma, name='update_rma'),
    path('schedule/new/printer', views.schedule, name="schedule"),
    path('schedule/update/new/printer', views.schedule_update, name="schedule_update"),
    path('cancel/printer/schedule', views.cancel_schedule, name="cancel_schedule"),
    path('schedule/update/both', views.both_update_schedule, name="both_update_schedule"),
    path('schedule/update/fixed', views.fixed_update_schedule, name="fixed_update_schedule"),
    path('schedule/update/delivery', views.delivery_update_schedule, name="delivery_update_schedule"),
    path('event', views.event, name="event"),
    path('about/', views.about, name='about'),
    path('reports', views.reports, name="reports"),
    path('waybill/options', views.waybill_options, name="waybill_options"),
    path('printer/options', views.printer_options, name="printer_options"),
    path('waybill/prompt', views.waybill, name='waybill_form'),
    path('waybill/pdf', views.waybillpdf, name='waybill_pdf'),
    path('waybill/pickup/pdf', views.pickup_pdf, name='pickup_pdf'),
    path('waybill/pickup/prompt', views.pickup, name='pickup_form'),
    path('waybills/references', views.waybills, name="waybills"),
    path('user/waybills/none_uploaded', views.user_waybills, name="user_waybills"),
    path('upload_waybill/<str:pk>', views.save_waybill_from_list, name='upload'),
    path('upload/waybill/', views.save_waybill, name='upload_waybill'),
    path('upload/waybill/pickup', views.save_pickup_waybill, name='upload_pickup'),
    path('view_waybill/<str:filename>', views.view_waybill, name='view_waybill'),
    path('download_waybill/<str:filename>', views.download_waybill, name='download_waybill'),
    path('report/stock/parts', views.parts, name="parts"),
    path('report/stock/parts/frequently/requests', views.frequently_used_parts, name="freq_parts"),
    path('stock/part/add', views.add_part, name="add_part"),
    path('stock/parts/management', views.part_management_options, name="part_options"),
    path('stock/part/stock/update', views.update_stock, name='update_stock'),
    path('stock/part/request', views.request_part, name='request_part'),
    path('stock/part/events', views.part_event, name='part_event'),
    path('approvals/pending', views.pending_approvals, name='pending_approvals'),
    path('approvals/cancelled/printer/pending', views.cancellation_requests, name='cancellation_requests'),
    path('approvals/client/added/pending', views.added_client_requests, name='client_requests'),
    path('approvals/part/added/pending', views.added_part_requests, name='part_requests'),
    path('approve_cancellation/<str:pk>', views.approve_cancellation_request, name='approve_cancellation'),
    path('reject_cancellation/<str:pk>', views.reject_cancellation_request, name='reject_cancellation'),
    path('approve_client/<str:pk>', views.approve_added_client_request, name='approve_client'),
    path('reject_client/<str:pk>', views.reject_added_client_request, name='reject_client'),
    path('approve_part/<str:pk>', views.approve_added_part_request, name='approve_part'),
    path('reject_part/<str:pk>', views.reject_added_part_request, name='reject_part'),
    path('update_client_maintenance/<str:pk>', views.update_client_maintenance, name='update_client_maintenance'),
    path('cancel_client_maintenance/<str:pk>', views.cancel_client_maintenance, name='cancel_client_maintenance'),
    path('client/schedule/maintenance', views.schedule_maintenance, name='schedule_maintenance'),
    path('client/maintenances', views.client_maintenance, name='client_maintenance'),
    path('ratings/options', views.rating_options, name="rating_options"),
    path('ratings/report', views.rating_report, name="rating_report"),
    path('ratings/report/summary', views.rating_summary, name="rating_summary"),
    path('rate_user/<uid>/<rid>', views.rate_user, name="rate_user"),
    path('training_rate/<uid>/<tid>/<rid>', training_rate, name="training_rate"),
    path('maintenance_rate/<uid>/<tid>', maintenance_rate, name="maintenance_rate"),
    path('trainings/assessments/options', views.training_options, name="training_options"),
    path('client/trainings', views.trainings, name="trainings"),
    path('update_client_training/<str:pk>', views.update_training, name='update_client_training'),
    path('cancel_client_training/<str:pk>', views.cancel_training, name='cancel_client_training'),
    path('technicians/trainings/assessments', views.assessments, name="assessments"),
    path('download_assessments/<str:pk>', views.download_assessments, name='download_assessments'),
    path('schedule/trainings', views.schedule_training, name="schedule_training"),
    path('accounts/portal', views.accounts_options, name="account_options"),
    path('accounts/portal/nhia/sla/accounts/report', views.nhia_sla, name="account_portal"),
    path('accounts/portal/nhia/printers/report', views.nhia_report, name="nhia_report"),
    path('update_ticket/<str:pk>', views.fix_ticket, name='update_ticket'),
    path('helpdesk/tickets', views.tickets, name="tickets"),
    path('procurement/options', views.procurement_options, name="procurement_options"),
    path('procurement/add/printer', views.add_purchased_printer, name="add_printer"),
    path('update_printer/<str:pk>', views.update_printer, name='update_printer'),
    path('procurement/printers', views.purchased_printers, name='purchased_printers'),
    path('procurement/client/printers', views.client_printers, name='client_printers'),
    path('report/nhia/printers', views.weekly_printers_report, name='weekly_printers_report'),

    # laminator urls
    path('laminator/options', views.laminator_options, name="laminator_options"),
    path('schedule/new/laminator', views.schedule_laminator, name="schedule_laminator"),
    path('schedule/update/laminator', views.laminator_update, name="laminator_update"),
    path('cancel/laminator/schedule', views.cancel_laminator_schedule, name="cancel_laminator_schedule"),
    path('schedule/update/new/laminator', views.laminator_schedule_update, name="laminator_schedule_update"),
    path('report/cancelled/laminator/schedules', views.cancelled_laminator_schedules, name="cancelled_laminator_schedules"),
    path('report/pending/laminators', views.pending_laminators, name="pending_laminators"),
    path('update_pending_laminator/<str:pk>', views.update_pending_laminator, name='update_pending_laminator'),
    path('cancel_pending_laminator/<str:pk>', views.cancel_pending_laminator, name='cancel_pending_laminator'),
    path('approvals/cancelled/laminators/pending', views.laminator_cancellation_requests, name='laminator_cancellation_requests'),
    path('approve_laminator_cancellation/<str:pk>', views.approve_laminator_cancellation_request, name='approve_laminator_cancellation'),
    path('reject_laminator_cancellation/<str:pk>', views.reject_laminator_cancellation_request, name='reject_laminator_cancellation'),
    path('reports/fixed/laminators', views.fixed_laminators, name="fixed_laminators"),
    path('procurement/add/laminator', views.add_purchased_laminator, name="add_laminator"),
    path('update_laminator/<str:pk>', views.update_laminator, name='update_laminator'),
    path('procurement/client/laminators', views.client_laminators, name='client_laminators'),
    path('laminator/report/user', views.user_laminator_report, name="user_laminator_report"),
    path('laminator_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.user_report_laminator_details,
         name='user_report_laminator_details'),
    path('report/client/laminators', views.client_laminator_report, name="client_laminator_report"),
    path('client_laminator_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.client_report_laminator_details,
         name='client_report_laminator_details'),

    # mrw urls
    path('mrw/options', views.mrw_options, name="mrw_options"),
    path('schedule/new/mrw', views.schedule_mrw, name="schedule_mrw"),
    path('schedule/update/mrw', views.mrw_update, name="mrw_update"),
    path('cancel/mrw/schedule', views.cancel_mrw_schedule, name="cancel_mrw_schedule"),
    path('schedule/update/new/mrw', views.mrw_schedule_update, name="mrw_schedule_update"),
    path('report/cancelled/mrw/schedules', views.cancelled_mrw_schedules, name="cancelled_mrw_schedules"),
    path('report/pending/mrws', views.pending_mrws, name="pending_mrws"),
    path('update_pending_mrw/<str:pk>', views.update_pending_mrw, name='update_pending_mrw'),
    path('cancel_pending_mrw/<str:pk>', views.cancel_pending_mrw, name='cancel_pending_mrw'),
    path('approvals/cancelled/mrws/pending', views.mrw_cancellation_requests, name='mrw_cancellation_requests'),
    path('approve_mrw_cancellation/<str:pk>', views.approve_mrw_cancellation_request, name='approve_mrw_cancellation'),
    path('reject_mrw_cancellation/<str:pk>', views.reject_mrw_cancellation_request, name='reject_mrw_cancellation'),
    path('reports/fixed/mrws', views.fixed_mrws, name="fixed_mrws"),
    path('update_mrw/<str:pk>', views.update_mrw, name='update_mrw'),
    path('procurement/client/mrws', views.client_mrws, name='client_mrws'),
    path('mrw/report/user', views.user_mrw_report, name="user_mrw_report"),
    path('mrw_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.user_report_mrw_details,
         name='user_report_mrw_details'),
    path('report/client/mrws', views.client_mrw_report, name="client_mrw_report"),
    path('client_mrw_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.client_report_mrw_details,
         name='client_report_mrw_details'),

    # iss urls
    path('iss/options', views.iss_options, name="iss_options"),
    path('schedule/new/iss', views.schedule_iss, name="schedule_iss"),
    path('schedule/update/iss', views.iss_update, name="iss_update"),
    path('cancel/iss/schedule', views.cancel_iss_schedule, name="cancel_iss_schedule"),
    path('schedule/update/new/iss', views.iss_schedule_update, name="iss_schedule_update"),
    path('report/cancelled/iss/schedules', views.cancelled_iss_schedules, name="cancelled_iss_schedules"),
    path('report/pending/iss', views.pending_iss, name="pending_iss"),
    path('update_pending_iss/<str:pk>', views.update_pending_iss, name='update_pending_iss'),
    path('cancel_pending_iss/<str:pk>', views.cancel_pending_iss, name='cancel_pending_iss'),
    path('approvals/cancelled/iss/pending', views.iss_cancellation_requests, name='iss_cancellation_requests'),
    path('approve_iss_cancellation/<str:pk>', views.approve_iss_cancellation_request, name='approve_iss_cancellation'),
    path('reject_iss_cancellation/<str:pk>', views.reject_iss_cancellation_request, name='reject_iss_cancellation'),
    path('reports/fixed/iss', views.fixed_iss, name="fixed_iss"),
    path('update_iss/<str:pk>', views.update_iss, name='update_iss'),
    path('procurement/client/iss', views.client_iss, name='client_iss'),
    path('iss/report/user', views.user_iss_report, name="user_iss_report"),
    path('iss_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.user_report_iss_details,
         name='user_report_iss_details'),
    path('report/client/iss', views.client_iss_report, name="client_iss_report"),
    path('client_iss_details/<str:pk>/<str:type>/<str:period>/<str:date>/<str:date2>', views.client_report_iss_details,
         name='client_report_iss_details'),

    # standard user urls
    path('maintenance_rate/<uid>/<tid>', maintenance_rate, name="maintenance_rate"),
    path('user/profile/ratings/<str:type>', user_ratings, name="user_ratings"),
    path('confirm_ticket/<str:pk>', confirm_ticket_status, name='confirm_ticket'),
    path('update_maintenance_u/<str:pk>', update_maintenance, name='update_maintenance'),
    path('cancel_maintenance_u/<str:pk>', cancel_maintenance, name='cancel_maintenance'),
    path('update_pending_laminator_u/<str:pk>', update_pending_laminator, name='update_pending_laminator_u'),
    path('cancel_pending_laminator_u/<str:pk>', cancel_pending_laminator, name='cancel_pending_laminator_u'),
    path('update_pending_mrw_u/<str:pk>', update_pending_mrw, name='update_pending_mrw_u'),
    path('cancel_pending_mrw_u/<str:pk>', cancel_pending_mrw, name='cancel_pending_mrw_u'),
    path('update_pending_iss_u/<str:pk>', update_pending_iss, name='update_pending_iss_u'),
    path('cancel_pending_iss_u/<str:pk>', cancel_pending_iss, name='cancel_pending_iss_u'),
]
